// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8t16EuCqoaLDD_aEmGVk73ZyvrfMwIGg',
    appId: '1:88844383960:web:8d4ad1accc76c2c79089ad',
    messagingSenderId: '88844383960',
    projectId: 'education-111a6',
    authDomain: 'education-111a6.firebaseapp.com',
    databaseURL: 'https://education-111a6-default-rtdb.firebaseio.com',
    storageBucket: 'education-111a6.firebasestorage.app',
    measurementId: 'G-NHS4PHGDEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_tYPlToWuu5UG1wIYF-Bgsa8Uba4MJg',
    appId: '1:88844383960:android:6a1642f8c41c512e9089ad',
    messagingSenderId: '88844383960',
    projectId: 'education-111a6',
    databaseURL: 'https://education-111a6-default-rtdb.firebaseio.com',
    storageBucket: 'education-111a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoxFKzzVrofbgoUNp1ZpTyBXwGr_x75zI',
    appId: '1:88844383960:ios:157580b2c5ed0bc99089ad',
    messagingSenderId: '88844383960',
    projectId: 'education-111a6',
    databaseURL: 'https://education-111a6-default-rtdb.firebaseio.com',
    storageBucket: 'education-111a6.firebasestorage.app',
    iosClientId:
        '88844383960-gaj6cqgdij4m46omm8r0qimn3ejg4v8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoxFKzzVrofbgoUNp1ZpTyBXwGr_x75zI',
    appId: '1:88844383960:ios:157580b2c5ed0bc99089ad',
    messagingSenderId: '88844383960',
    projectId: 'education-111a6',
    databaseURL: 'https://education-111a6-default-rtdb.firebaseio.com',
    storageBucket: 'education-111a6.firebasestorage.app',
    iosClientId:
        '88844383960-gaj6cqgdij4m46omm8r0qimn3ejg4v8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8t16EuCqoaLDD_aEmGVk73ZyvrfMwIGg',
    appId: '1:88844383960:web:d5ea02de631a1a209089ad',
    messagingSenderId: '88844383960',
    projectId: 'education-111a6',
    authDomain: 'education-111a6.firebaseapp.com',
    databaseURL: 'https://education-111a6-default-rtdb.firebaseio.com',
    storageBucket: 'education-111a6.firebasestorage.app',
    measurementId: 'G-W0L3QY4CYH',
  );
}
